### ISSUE TITLE
Could I use this plugin to develop a native live stream camera? 

### ISSUE THREAD

**Issue by chhonhourseng** [buijs-dev/klutter-dart#8]
Could I use this plugin to develop a native live stream camera? If so, could you guide me on how to view the native screen?

**Comment by buijs-dev** [comment]
Technically it should be possible but the generated Flutter Widgets are not designed with that in mind. I would have to look into it. For now I would not use Klutter but instead write the native code in iOS/Android yourself.

**Comment by chhonhourseng** [comment]
Yes, thank you
