### ISSUE TITLE
Does the plugin support expect functions?

### ISSUE THREAD

**Issue by lemkoleg** [buijs-dev/klutter-dart#9]
Does the plugin support expect functions?

**Comment by buijs-dev** [comment]
Can you explain what you mean?

**Comment by lemkoleg** [comment]
If I have an implementation of expect function or class (eg KotlinPlayer), with implementation for each platform separately (eg ExoPqlayer and AvPlayer initialization), does the plugin implement this class in dart code?

**Comment by buijs-dev** [comment]
Ah you mean the Kotlin expect/actual mechanism! Of course that works. An example is in the tutorial [here].(https://buijs.dev/klutter-2/). It's a bit outdated though, will update it soon. But yes, you can use expect in your Kotlin code.

**Comment by lemkoleg** [comment]
Thank you.  I will try.  only, for some reason, the plugin creates a new project without the ios and android directories.  I think I'll figure this out.  I just started looking at your plugin

**Comment by buijs-dev** [comment]
See my last comment [here](https://github.com/buijs-dev/klutter/issues/22) to create a new project. Let me know if you get it up and running?

**Comment by lemkoleg** [comment]
Ок

**Comment by lemkoleg** [comment]
Hello.
We managed to create the project. The reason why the project was not created correctly
is as follows:
  when you install Flutter plugins, in IDE (Intellij or Android Studio)
  The "New Flutter Project" button appears. When you install the Klutter plugin,
  this button changes the name to "New Klutter Project".
  If you create a project using this button, the project is not created correctly.
  You need to select "New Project", and then select the project type "Flutter".
 
  P.S. Note to other users.

**Comment by buijs-dev** [comment]
No that's not correct. The "create Klutter project" button is used to create a Klutter project, not Flutter.

**Comment by lemkoleg** [comment]
Try it yourself.  Or maybe there's something wrong with my system

**Comment by lemkoleg** [comment]
Will a project created in the way I described work?

**Comment by buijs-dev** [comment]
> Try it yourself. Or maybe there's something wrong with my system

Which IDE do you use? Intellij or Android Studio? What platform (Windows or macOS)?

I updated the tutorial for [2023.2.1.beta](https://buijs.dev/klutter-3/). Does it work for you if you follow these steps?

**Comment by lemkoleg** [comment]
> ... You need to select "New Project", and then select the project type "Flutter".
> 

I'm sorry. I made a mistake: instead of the last name Flutter, I meant Klutter

**Comment by buijs-dev** [comment]
Okay np!

**Comment by lemkoleg** [comment]
MacOS Venture
IntelliJ IDEA 2023.2.2 (Ultimate Edition)
Android Studio Giraffe | 2022.3.1 Patch 2

**Comment by lemkoleg** [comment]
I updated the versions of Kotlin/Gradle/Android plugin, and now my project is not building due to errors. What can't be updated? My Kotlin library was written in Kotlin version 1.9.10. I'm afraid that if I downgrade the version, I will have to fix something (Here is a link to the project
https://github.com/lemkoleg/jsocket_klutter
If you have time, please take a look

**Comment by buijs-dev** [comment]
> I updated the versions of Kotlin/Gradle/Android plugin, and now my project is not building due to errors. What can't be updated? My Kotlin library was written in Kotlin version 1.9.10. I'm afraid that if I downgrade the version, I will have to fix something (Here is a link to the project https://github.com/lemkoleg/jsocket_klutter If you have time, please take a look

Okay so few things:

1. Kotlin 1.9 is not supported (yet) and will possible give you problems because it is not compatible with the KSP version.
2. In the platform/build.gradle.kts you're changing the name of the XCFramework to JSOCKETIosLib. You should not do that because some Gradle tasks will then have a different name. So change it back on line 58 to `    val xcfName = "Platform"`.
3. In the platform/build.gradle.kts you changed Android target/min/compile versions which are untested. 

I recommend to create a new project (using the project wizard), without changing the default setup (kotlin/android/plugin versions). Build the code and run it first to check if everything works. After that start adding your code in the platform module.

**Comment by lemkoleg** [comment]
Hello. When are you planning to update the plugin to run Kotlin version 1.9? It seems like KSP already supports

**Comment by buijs-dev** [comment]
I'm working on windows support and will have a look at updating dependencies after that. I can't give an ETA for now.
